export const CHANNELS = [
  'clients:list',
  'clients:get',
  'clients:create',
  'clients:update',
  'clients:archive',
  'clients:unarchive',
  'clients:anonymize',
  'clients:account',
  'teachers:list',
  'teachers:get',
  'teachers:create',
  'teachers:update',
  'teachers:account',
  'plans:list',
  'plans:create',
  'plans:update',
  'sales:create',
  'sales:void',
  'payments:create',
  'payments:void',
  'consumptions:create',
  'consumptions:void',
  'payouts:create',
  'payouts:void',
  'dashboard:get',
  'waivers:create',
  'waivers:void',
  'settings:get',
  'settings:update',
  'backup:export',
  'backup:restore',
] as const;

export type Channel = (typeof CHANNELS)[number];
